- name: Create kubelet service override directory
  file: path=/etc/systemd/system/kubelet.service.d state=directory
- name: Configure kubelet service
  template: src=kubelet-override.conf.j2 dest=/etc/systemd/system/kubelet.service.d/override.conf

- name: Ensure kubelet service is running
  service: name=kubelet state=started
- name: Ensure kubelet service is enabled
  service: name=kubelet enabled=yes

- name: Install kube-proxy pod
  template: src=kube-proxy.json.j2 dest=/etc/kubernetes/manifests/kube-proxy.json
- name: Wait for kube-proxy to start (up to 5 minutes)
  wait_for:  port=10256 timeout=300
