- name: Create kubelet service override directory
  file: path=/etc/systemd/system/kubelet.service.d state=directory
- name: Configure kubelet service
  template: src=kubelet-override.conf.j2 dest=/etc/systemd/system/kubelet.service.d/override.conf

- name: Ensure kubelet service is running
  service: name=kubelet state=started
- name: Ensure kubelet service is enabled
  service: name=kubelet enabled=yes

- name: Create service file
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
  register: create_kube_proxy_service_result
- name: Reload service file
  command: systemctl daemon-reload
  when: create_kube_proxy_service_result.changed

- name: Ensure kube-proxy service is running
  service: name=kube-proxy state=started
- name: Ensure kube-proxy service is enabled
  service: name=kube-proxy enabled=yes
