- name: Create flannel deployment file
  template: src=flannel.yml.j2 dest=/etc/kubernetes/flannel.yml
  register: flannel_deployment_file_result
  when: kube_master_node

- name: Apply flannel deployment
  command: kubectl apply -f /etc/kubernetes/flannel.yml
  when: kube_master_node and flannel_deployment_file_result.changed

- name: Wait for flannel env file (up to 5 minutes)
  wait_for: path=/var/run/flannel/subnet.env timeout=300
- name: Read cidr from flannel env file
  command: grep FLANNEL_SUBNET= /var/run/flannel/subnet.env
  register: flannel_subnet_result
  changed_when: false
- set_fact: flannel_subnet={{ flannel_subnet_result.stdout.split('=')[1] }}
- set_fact: flannel_ip={{ flannel_subnet.split('/')[0] }}
- name: Configure docker for flannel subnet
  lineinfile: path=/etc/sysconfig/docker regexp=^DOCKER_BIP= line=DOCKER_BIP={{ flannel_subnet }}
- name: Restart docker service
  service: name=docker state=restarted
  when: ansible_docker0 is not defined or ansible_docker0.ipv4.address != flannel_ip
