- name: Ensure kubectl is installed
  package:
    name: kubectl-{{ kube_node_version }}
    state: installed
- name: Ensure config directories exist
  file:
    path: /var/lib/{{ item }}
    state: directory
  loop:
    - kubelet
    - kube-proxy
