- name: Ensure base directory exists
  file: path=/srv/kubernetes state=directory
- include: install-packages.yml
  tags:
  - install-packages
  - install-packages-kube
- include: configure-services.yml
  tags:
  - configure-services
  - configure-services-kube
