- include: generate-certs.yml
  tags:
  - generate-certs
  - generate-certs-kube
- include: install-packages.yml
  tags:
  - install-packages
  - install-packages-kube
- include: configure-services.yml
  tags:
  - configure-services
  - configure-services-kube
