- include_tasks: install-kube-node-packages.yml
  tags: kube_node_packages

- name: Copy kubeconfig files
  template:
    dest: /var/lib/{{ item }}/kubeconfig
    src: "{{ item }}-kubeconfig.j2"
  loop:
    - kubelet
    - kube-proxy
  tags: kube_config

- name: Include install-master-pods.yml
  when: kube_master
  include_tasks: install-master-pods.yml
  tags: kube_master_pods

- name: Include install-kube-proxy.yml
  include_tasks: install-kube-proxy.yml
  tags: kube_proxy
