- include: generate-certs.yml
  tags:
  - generate-certs
  - generate-certs-kube
- include: install-packages.yml
  tags:
  - install-packages
  - install-packages-kube
- include: kube-master.yml
  when: kube_master_node
  tags:
  - kube-master
- include: configure-services.yml
  tags:
  - configure-services
  - configure-services-kube
- include: flannel.yml
  tags:
  - kube-master
  - flannel
